clear
clc
I=imread('banner_button_4_lassing.jpg');
%I=imresize(I,0.5);
mask=maskImage(I);
q=double(mask);
ind=find(q==1);
s=size(q);
[R,C]=ind2sub(s,ind);
%q=q.*(-exp(5));
q=q.*(-1000);
%q(isnan(q))=1;
q(q==0)=1;
%t=repmat(q,1,1,3);
%I=im2double(I);
%w=I.*t;
%w=im2uint8(w);
[Ic,T]=carv(I,floor((max(R)-min(R)+1)/2),floor((max(C)-min(C)+1)/2),q);
%[Ic,T]=carv(I,0,max(C)-min(C)+1,q);
T1=T;
%video_creator2
m=seamInsertion(I,T,q);
video_creator