clear
clc
I=imread('8.jpg');
%I=imresize(I,0.8);
mask=maskImage(I);
q=double(mask);
ind=find(q==1);
s=size(q);
[R,C]=ind2sub(s,ind);
%q=q.*(-exp(5));
q=q.*(-1000);
%q(isnan(q))=1;
q(q==0)=1;
%t=repmat(q,1,1,3);
%I=im'2double(I);
%w=I.*t;
%w=im2uint8(w);
nr=max(R)-min(R)+1;
nc=max(C)-min(C)+1;
[Ic,T]=carv(I,nr,nc,q);
%[Ic,T]=carv(I,0,max(C)-min(C)+1,q);
T1=T;
%video_creator2
m=seamInsertion(I,T,q);
video_creator
imwrite(im2uint8(Ic),'9v.jpg');
imwrite(im2uint8(m{end}),'9final.jpg');